### ISSUE TITLE
Drones don't prioritize building structures

### ISSUE THREAD

**Issue by TobleroneSwordfish** [stonepillars/goon-flock#11]
### Labels

[AI]

### Description

Drones don't prioritize building structures

### Steps to reproduce

1. Place a structure with Fabricate Structure
2. Watch as your drones use all their resources converting random tiles instead of building it

### Expected Behavior

Either set the priority of the deposit materials AI task higher or let us target the structure with Designate Priority Tile

**Comment by amylizzle** [comment]
Fairly related to this: drones shouldn't really build tiles - that's a) the flockbit's job and b) really inefficient use of resources

They should definitely be able to, but it should be something that they do only if there's nothing else to do, and they should prioritise doors and stuff when they do so
