### ISSUE TITLE
Make some abilities more intuitive

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#12]
### Labels

[FEATURE]

### Description

Some actions are not at all obvious how to do.

### Things which are not obvious (probably not a complete list)
1. Taking control of a drone - Currently requires click+drag self onto drone
2. Caging an enemy mob - requires hitting the mob with the nanite spray in the disarm intent while they are stunned. seriously.

### Expected Behavior

an idiot should be able to figure this out almost immediately

**Comment by FlameArrow57** [comment]
https://github.com/stonepillars/goon-flock/discussions/226
