### ISSUE TITLE
Flockdrones cannot escape pods without rescue from another drone

### ISSUE THREAD

**Issue by stonepillars** [stonepillars/goon-flock#137]
### Labels

[BUG]

### Description

Flockdrones cannot escape from a pod without help from another drone

### Steps to reproduce

1. Be flockmind/trace
2. Take control of drone
3. Enter pod
4. Release control of drone
5. Drone sad

### Expected Behavior

I dunno it getting out or something

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/65367576/162542846-064fbac4-bfa0-4871-81d4-503004de2b2c.png)

**Comment by amylizzle** [comment]
honestly the proper fix for this should probably be drones can't get in pods.
