### ISSUE TITLE
Setting drones on fire causes runtimes

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#156]
### Labels

[BUG]

### Description

Start a plasma fire, watch the runtimes roll in

### Steps to reproduce

1. Start a plasma fire
2. Move drone into it
3. oh no runtimes
4. turn off breakpoint on runtime, watch the drones be bad at extinguishing themselves.

### Expected Behavior

Drones should handle burning status (and probably other status things)

**Comment by stonepillars** [comment]
Solved by #157, which is an upstream bug.

**Comment by amylizzle** [comment]
Fixed already upstream, close on upstream merge
