### ISSUE TITLE
Flock rift can be opened in arrivals

### ISSUE THREAD

**Issue by TobleroneSwordfish** [stonepillars/goon-flock#160]
### Labels

[BUG]

### Description

Arrivals is usually considered off-limits so flock should not be able to place their rift there.

### Steps to reproduce

1. Load map with arrivals
2. Place rift there

### Expected Behavior

It shouldn't be able to

**Comment by amylizzle** [comment]
#54 should have fixed this. Maybe IS_ARRIVALS() isn't working properly?

**Comment by FlameArrow57** [comment]
Might be because you are testing in admin mode, admins can spawn the rift in arrivals (copied from blob).

**Comment by TobleroneSwordfish** [comment]
![image](https://user-images.githubusercontent.com/20713227/163728439-afd03520-c2d4-42cb-93e6-dac8ea7e9255.png)
Yep, it works fine outside of admin mode, closing
