### ISSUE TITLE
Flock needs a way to deal with plasma

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#161]
### Labels

[FEATURE]

### Description

Popping a bunch of plasma cans and starting a fire is an effective way to kill flock

### Steps to reproduce

1. Be flock
2. get rekt by a plasma fire
3. be sad about it

### Expected Behavior

We should maybe have a structure that sucks up atmosphere, or processes it in some way

**Comment by FlameArrow57** [comment]
https://github.com/stonepillars/goon-flock/discussions/227
