### ISSUE TITLE
Flockmind is unable to do anything after partitioning.

### ISSUE THREAD

**Issue by Mobilfan** [stonepillars/goon-flock#168]
### Labels

[BUG]

### Description

When partitioning you are unable to use any abilities or open the menu until the 30 seconds are up.

### Steps to reproduce

1. Be flock
2. Partition mind
3. Press any ability

### Expected Behavior

I expected to be able to keep doing stuff.

**Comment by FlameArrow57** [comment]
It was implemented the same way as done with wraith when making a poltergeist, so kept it this way. Can change if wanted.

**Comment by Mobilfan** [comment]
Seems weird to paralyze the flockmind for the waiting period.
