### ISSUE TITLE
First action bar when supplying materials to construction is blue

### ISSUE THREAD

**Issue by Mobilfan** [stonepillars/goon-flock#169]
### Labels

[BUG]

### Description

When a drone supplies materials to construction, the first action bar is blue and the following ones green.

### Steps to reproduce

1. Be flock
2. Make construction
3. Watch a drone supply materials

### Expected Behavior

The action bar should be green (i think)

**Comment by amylizzle** [comment]
I kinda like this tbh, it's like starting the action is different to continuing the action.

I'm happy to call this a feature rather than a bug, but feel free to PR if you disagree.
