### ISSUE TITLE
Flockmind should be able to deconstruct walls and machinery

### ISSUE THREAD

**Issue by Mobilfan** [stonepillars/goon-flock#170]
[FEATURE]

### What?

Flockmind should be able to designate walls, machinery and probably flock stuff for deconstruction.

### Why?

Some things don't get converted and linger around, which looks weird. Also being able to deconstruct walls would prevent crew from just walling the flock in.

**Comment by FlameArrow57** [comment]
Walls can be deconstructed, deconstructing is done using nanite spray on harm intent. Closets and doors can be deconstructed too. Other stuff to be done later.

**Comment by FlameArrow57** [comment]
https://github.com/stonepillars/goon-flock/discussions/229
