### ISSUE TITLE
Wall-Mounted Defibs Provide Infinite Resources

### ISSUE THREAD

**Issue by Wisemonster** [stonepillars/goon-flock#174]
### Labels

[BUG]

### Description

Picking up a wall-mounted defib and putting it in your disintegration reclaimer allows you to get resources from the defib, and moving away from the source of the defib will return it back to it's spot, allowing farming of resources

### Steps to reproduce

1. Find a wall-mounted defib
2. Stick the defib into your reclaimer
3. Wait a second, then move away from the wall-mounted defib's home
4. Watch as the defib is removed from your reclaimer, returned to it's home, and see that you generated some resources
5. Repeat until full of resources

### Expected Behavior

For the defib to not be a resource farm

**Comment by Wisemonster** [comment]
Apparently, this also applies to phones as well

**Comment by FlameArrow57** [comment]
Ok, so was playing around, seems that defibs do get destroyed, even through this method? Though, clicking on the defib mount will recreate the defib, which then has zero health. Sounds more like upstream issue. Was with defib in cogmap 2 medbay operating theater to the right of cryo tubes.

Tried it on phone in chemistry, appeared to be destroyed right away? Could be issue in future for health changes, but couldn't reproduce.

**Comment by amylizzle** [comment]
Fixed upstream, close on upstream merge
