### ISSUE TITLE
Can Drag Items/People While Sprinting Over Flock Tiles As A Flock Drone

### ISSUE THREAD

**Issue by Wisemonster** [stonepillars/goon-flock#175]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Find someone/something on your turf/tiles
2. Grab them/it
3. Start sprinting deeper in your territory
4. Take your victim/item with you, unable to fight back.

### Expected Behavior

To stop dragging someone when I start sprinting over flock tiles

### Additional Information & Screenshots

Considering this allows someone near the edge of flock territory to be incapacitated and very quickly brought somewhere where there is more flock drones, this seems like something that is a problem.

**Comment by FlameArrow57** [comment]
#92 fixes this.
