### ISSUE TITLE
Obsessive bell ringing

### ISSUE THREAD

**Issue by Mobilfan** [stonepillars/goon-flock#182]
### Labels

[BUG]

### Description

Autonomous flockdrones will keep ringing the bell forever

### Steps to reproduce

1. Be flock
2. Have flockdrone
3. Have the drone be next to a service bell
4. It may or may not start ringing the bell, but if it starts, it's dedicated

### Expected Behavior

Probably to convert the bell or something

**Comment by amylizzle** [comment]
Fixed by #185
