### ISSUE TITLE
Let flockmind set priorities

### ISSUE THREAD

**Issue by Mobilfan** [stonepillars/goon-flock#195]
[FEATURE]

Right now the autonomous drones rely on pre programmed priorities to function, but what if the flockmind could change what is being prioritized? Maybe just prioritize one thing at a time if it's too hard to set a whole list.

**Comment by amylizzle** [comment]
I'd say #181 closes this but I guess that's specific vs general orders? IDK

**Comment by Mobilfan** [comment]
Yea this is more about a way to influence the entire flock, instead of just one drone (as there could be many many drones).

**Comment by FlameArrow57** [comment]
https://github.com/stonepillars/goon-flock/discussions/228
