### ISSUE TITLE
Flocktraces do not have antag overlays while in drones

### ISSUE THREAD

**Issue by TobleroneSwordfish** [stonepillars/goon-flock#236]
### Labels

[BUG]

### Description

Not actually sure if they do at all

### Steps to reproduce

1. Be flock
2. See other flocktrace in drone
3. Be unable to tell they are sentient

### Expected Behavior

They should have overlays and possibly flock should have custom antag overlays since a big V isn't very flocky

**Comment by FlameArrow57** [comment]
Will be fixed with https://github.com/stonepillars/goon-flock/discussions/203

**Comment by FlameArrow57** [comment]
You mean seeing a Flocktrace in a Flockdrone as a ghost?

**Comment by amylizzle** [comment]
Duplicate of #235

**Comment by amylizzle** [comment]
Not sure this is as much of a dupe as I thought, since it's more about traces/minds seeing other traces/minds in drones

**Comment by FlameArrow57** [comment]
Will be fixed by what's worked on in #203.

**Comment by TobleroneSwordfish** [comment]
I'mma close this since half of it has been fixed and the other part has a separate issue in #237
