### ISSUE TITLE
As flockmind/trace it isn't obvious which drones are controlled

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#237]
### Labels

[BUG][FEATURE]

### Description

They all look the same

### Steps to reproduce

1. Be flockmind/trace
2. Have a drone be possessed by another trace
3. No visible indication of that except behaviour

### Expected Behavior

There should be an icon or something

**Comment by FlameArrow57** [comment]
Will be fixed with https://github.com/stonepillars/goon-flock/discussions/203

**Comment by amylizzle** [comment]
Fixed by #276
