### ISSUE TITLE
Item stacking bug

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#240]
### Labels

[BUG]

### Description

Stacking items while they're being digested is messed up

### Steps to reproduce

1. Pick up a stack of things
2. Pick up some more things that can add to the stack
3. Click on the digesting stack with the more things
4. weirdness

### Expected Behavior

Probably shouldn't work at all? or should just add more stuff to the stack being digested?

**Comment by stonepillars** [comment]
Possibly involves test-merge of #208 during the playtest

**Comment by amylizzle** [comment]
pretty sure it doesn't, I think I've seen this one before with a stack of char

**Comment by amylizzle** [comment]
I'm thinking this is an upstream issue, and should be wontfix. Stacking is done differently for every item time and it is an abomination. Stacking components when.
