### ISSUE TITLE
Taking control of a drone sometimes makes it start moving in some direction

### ISSUE THREAD

**Issue by pali6** [stonepillars/goon-flock#248]
### Labels

[BUG]

### Description

Need to tap the direction to stop

### Steps to reproduce

1. Take control of a drone under ✨some circumstances✨ (presumably when it's walking somewhere?)
2. Watch it move until you tap that directional key

### Expected Behavior

Move stops when you take control of it

**Comment by amylizzle** [comment]
There are so many things stopping this from happening, I have no idea why it keeps doing it.
```
	src.controller = pilot
	walk(src, 0)
	src.ai.stop_move() //cancel any pathing that's happening
	src.is_npc = 0
	src.dormant = 0
	src.anchored = 0
```

I am considering that it might be race condition type thing.
