### ISSUE TITLE
Drones should eat critters

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#25]
### Labels

[FEATURE]

### Description

There's no interaction with critters right now. We should eat them.

### Steps to reproduce

1. Be a drone
2. Ignore a critter

### Expected Behavior

Eat the critter

### Additional Information & Screenshots

Probably just make this a use case for the flockcage? It looks from comments in the code that this was intended but never implemented.

**Comment by TobleroneSwordfish** [comment]
Just don't make them pick fights with monkeys or the flock won't stand a chance
