### ISSUE TITLE
Flockdrones getting stuck on plastic flaps

### ISSUE THREAD

**Issue by TobleroneSwordfish** [stonepillars/goon-flock#261]
### Labels

[BUG]

### Description

Flockdrones seem to think they can walk through plastic flaps but are proven wrong when they try to, leading to them getting stuck.

### Steps to reproduce

1. Order a drone to do something on the other side of plastic flaps

### Expected Behavior

Either drones should be able to pass them due to being short (are they actually short?) or should know that they are impassable

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/20713227/167072473-3ce58d67-3a4a-4fc4-b376-53115162f183.png)
The drone desires beepsky's diary

**Comment by TobleroneSwordfish** [comment]
Upstream fix here: https://github.com/goonstation/goonstation/pull/8481

**Comment by FlameArrow57** [comment]
Can be closed now I think?
