### ISSUE TITLE
Animation issue still present for containers

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#269]
### Labels

[BUG]

### Description

Containers (ie, toolboxes) get animated by the absorber and drop still animated

### Steps to reproduce

1. Start in spawn location on cog2
2. wait a minute
3. oh look, toolboxes, prescription glasses boxes, and medboxes doin wibbly stuff on the floor

### Expected Behavior

Things that are dropped should lose the animation.

**Comment by FlameArrow57** [comment]
Idk, seemed to work fine when controlling a drone. Maybe something AI related, or related to #271?
