### ISSUE TITLE
TGUI - No icon for depositing

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#28]
### Labels

[BUG]

### Description

No icon for the depositing action

### Steps to reproduce

1. open flock TGUI 
2. drones doing stuff
3. drones depositing
4. no icon

### Expected Behavior

neat icon

**Comment by TobleroneSwordfish** [comment]
I'm going to go find the actual list of tasks and make sure there's icons for all of them

**Comment by amylizzle** [comment]
> I'm going to go find the actual list of tasks and make sure there's icons for all of them

code/mob/living/critter/ai/flock/flocktasks.dm
