### ISSUE TITLE
Need a way to cancel a tealprint

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#32]
### Labels

[FEATURE]

### Description

Oh no, I put a tealprint down wrong, whatever shall I do?

### Steps to reproduce

1. Put down a tealprint in the wrong place
2. regret it

### Expected Behavior

I'm not sure how this should happen exactly, but some way of cancelling construction and dropping any resources that were stored within

**Comment by TobleroneSwordfish** [comment]
Right click verb maybe?
