### ISSUE TITLE
Priority designation of tiles does not seem to work too well

### ISSUE THREAD

**Issue by FlameArrow57** [stonepillars/goon-flock#42]
### Labels

[BUG]

### Description

Priority designating tiles does not seem to work very well. 

### Steps to reproduce

1. Be Flockmind.
2. Priority designate a tile for capture.

### Expected Behavior

I would expect a tile to be converted shortly after designating it, but it takes a while, if converted at all.

**Comment by stonepillars** [comment]
This is related to #24
In general, the priority tasks should be fixed since flock drones almost never do tiles anymore because of the weighting.
