### ISSUE TITLE
Someone can be caged by at least two other Flockdrones at the same time

### ISSUE THREAD

**Issue by FlameArrow57** [stonepillars/goon-flock#48]
### Labels

[BUG]

### Description

If someone is being caged, another Flockdrone can start its cage process of the person.

### Steps to reproduce

1. A person is being caged by a Flockdrone with another Flockdrone nearby.

### Expected Behavior

The person should only be caged by one Flockdrone.

**Comment by amylizzle** [comment]
So long as they don't pay the cost twice, I think this is good behaviour to keep. The reason being: in a combat situation, the drones will be trying to cage the enemies, and the enemies will be trying to interrupt that. If multiple drones are caging one enemy, it means multiple targets need to be taken out to prevent the caging.

**Comment by stonepillars** [comment]
Closed as intentional
