### ISSUE TITLE
TGUI does not properly handle flockbits

### ISSUE THREAD

**Issue by stonepillars** [stonepillars/goon-flock#53]
### Labels

[bug]

### Description

TermOS Error when opening TGUI Panel with flockbits

### Steps to reproduce

1. Become flockmind
2. Plunk down the egg
3. Split one of your drones into flockbits
4. Open flock panel
5. See error

### Expected Behavior

No error

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/65367576/158485412-5adb7648-f971-458c-9e8e-f50ce66da88d.png)

**Comment by TobleroneSwordfish** [comment]
I can't reproduce this, flockbit data doesn't even seem to be sent to the UI:
![image](https://user-images.githubusercontent.com/20713227/158488142-0170a86b-459c-4610-8541-6f940db79514.png)

**Comment by FlameArrow57** [comment]
I got the same issue.

**Comment by TobleroneSwordfish** [comment]
I guess I'll just add some null checks around where I think this is coming from and hope it fixes it.
