### ISSUE TITLE
Beepsky can open Flockdoors

### ISSUE THREAD

**Issue by FlameArrow57** [stonepillars/goon-flock#87]
### Labels

[BUG]

### Description

Beepsky can open Flockdoors

### Steps to reproduce

1. Watch Beepsky patrol by Flockdoors

### Expected Behavior

For Beepsky to not be able to move through them.

**Comment by stonepillars** [comment]
Beepsky is the law

**Comment by amylizzle** [comment]
I forgot I looked into this and I'm not sure it can be fixed without overriding the door open proc. Bots have a flag that is used to basically force open any door.

**Comment by TobleroneSwordfish** [comment]
Didn't they have to remove armoury access from beepsky a while back?
