### ISSUE TITLE
Sentinel runtimes on fire

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#9]
### Labels

[BUG]

### Description

animate() call is glitched

### Steps to reproduce

1. build sentinel
2. build collector to power it
3. spawn human/clone
4. designate as enemy
5. sentinel tries to fire
6. runtime

sentinel:83 Exception has occurred: invalid object type 0:0

### Expected Behavior

zap

**Comment by TobleroneSwordfish** [comment]
oof

**Comment by amylizzle** [comment]
looks like it uses something that isn't implemented anymore? filter_data? I investigate
